{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "d:\\DestinyFolder\\DestinyRecaps\\DestinyRecapsApi\\serverproject\n"
     ]
    }
   ],
   "source": [
    "# DIRECTORY SET\n",
    "import os\n",
    "import sys\n",
    "from pathlib import Path\n",
    "base_dir=Path(os.getcwd()).parent\n",
    "# os.chdir(os.path.join(base_dir, 'serverproject'))\n",
    "os.chdir(base_dir)\n",
    "print(os.getcwd())\n",
    "\n",
    "# Load dotenv\n",
    "import dotenv\n",
    "dotenv.load_dotenv()\n",
    "\n",
    "# DJANGO SETUP\n",
    "import django\n",
    "sys.path.append(os.path.abspath(''))\n",
    "os.environ.setdefault(\"DJANGO_SETTINGS_MODULE\", \"serverproject.settings\")\n",
    "django.setup()\n",
    "\n",
    "# Import async modules\n",
    "import asyncio\n",
    "from asgiref.sync import sync_to_async\n",
    "\n",
    "# Import display modules\n",
    "from IPython.display import display, Markdown\n",
    "\n",
    "# Import other modules\n",
    "import faiss\n",
    "\n",
    "# import reloading\n",
    "from importlib import reload"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "video_id=\"H-XdAZC9U7M\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      ".%(ext)s\n"
     ]
    }
   ],
   "source": [
    "print('.%(ext)s')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<yt_dlp.YoutubeDL.YoutubeDL object at 0x000002A41D9A1B90>\n"
     ]
    }
   ],
   "source": [
    "import yt_dlp\n",
    "\n",
    "folder_path=\"destinyapp/working_folder/working_audio/\"\n",
    "\n",
    "# Set download parameters\n",
    "ydl_opts = {\n",
    "    'format': 'bestaudio/best',\n",
    "    'outtmpl': folder_path+'raw'+'.%(ext)s',#os.path.join(output_folder,output_name)+'.%(ext)s',\n",
    "    'age_limit': 21, \n",
    "    'cookiesfrombrowser': ('firefox',),\n",
    "    'config-location': 'yt-dlp.conf',\n",
    "}\n",
    "# ydl_opts = {\n",
    "#     'config-location': 'yt-dlp_t.conf',\n",
    "# }\n",
    "\n",
    "# # delete previous audio file with 'raw' in the name\n",
    "# audio_dir_files=os.listdir(folder_path)\n",
    "# for file_name in audio_dir_files:\n",
    "#     if 'raw' in file_name:\n",
    "#         os.remove(folder_path+file_name)\n",
    "#         break\n",
    "\n",
    "with yt_dlp.YoutubeDL(ydl_opts) as ydl:\n",
    "    print(ydl)\n",
    "    # ydl.download(['https://youtu.be/'+video_id])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[youtube] Extracting URL: https://youtu.be/H-XdAZC9U7M\n",
      "[youtube] H-XdAZC9U7M: Downloading webpage\n",
      "[youtube] H-XdAZC9U7M: Downloading ios player API JSON\n",
      "[youtube] H-XdAZC9U7M: Downloading player 1c78e434\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: [youtube] H-XdAZC9U7M: nsig extraction failed: You may experience throttling for some formats\n",
      "         n = zBlqNMCzEB02BS2kt5 ; player = https://www.youtube.com/s/player/1c78e434/player_ias.vflset/en_US/base.js\n",
      "WARNING: [youtube] H-XdAZC9U7M: nsig extraction failed: You may experience throttling for some formats\n",
      "         n = YTTAZsEief27sM-0Hk ; player = https://www.youtube.com/s/player/1c78e434/player_ias.vflset/en_US/base.js\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[youtube] H-XdAZC9U7M: Downloading m3u8 information\n",
      "[info] Testing format 609\n",
      "[info] H-XdAZC9U7M: Downloading 1 format(s): 609+140\n",
      "[hlsnative] Downloading m3u8 manifest\n",
      "[hlsnative] Total fragments: 36\n",
      "[download] Destination: 25th anniversary of destructive Salt Lake City tornado [H-XdAZC9U7M].f609.mp4\n",
      "[download] 100% of   16.76MiB in 00:00:02 at 6.99MiB/s                   \n",
      "[download] Destination: 25th anniversary of destructive Salt Lake City tornado [H-XdAZC9U7M].f140.m4a\n",
      "[download] 100% of    2.90MiB in 00:00:00 at 33.74MiB/s  \n",
      "[Merger] Merging formats into \"25th anniversary of destructive Salt Lake City tornado [H-XdAZC9U7M].mp4\"\n",
      "Deleting original file 25th anniversary of destructive Salt Lake City tornado [H-XdAZC9U7M].f609.mp4 (pass -k to keep)\n",
      "Deleting original file 25th anniversary of destructive Salt Lake City tornado [H-XdAZC9U7M].f140.m4a (pass -k to keep)\n"
     ]
    }
   ],
   "source": [
    "folder_path=\"destinyapp/working_folder/working_audio/\"\n",
    "ydl_opts = {\n",
    "    'format': 'bestaudio/best',\n",
    "    'outtmpl': folder_path+'raw'+'.%(ext)s',#os.path.join(output_folder,output_name)+'.%(ext)s',\n",
    "    'age_limit': 21, \n",
    "    'username': 'oauth2',\n",
    "    'password': '',\n",
    "    'verbose': True,\n",
    "}\n",
    "\n",
    "ydl_opts = {\n",
    "    # 'P': os.path.join(os.getcwd(),'yt-dlp.conf'),\n",
    "    'usenetrc': True,\n",
    "    'netrc_location': os.path.join(os.getcwd(),'yt-dlp.netrc'),\n",
    "}\n",
    "with yt_dlp.YoutubeDL(ydl_opts) as ydl:\n",
    "    ydl.params\n",
    "\n",
    "    ydl.download(['https://youtu.be/'+video_id])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'usenetrc': True,\n",
       " 'netrc_location': 'd:\\\\DestinyFolder\\\\DestinyRecaps\\\\DestinyRecapsApi\\\\serverproject\\\\yt-dlp.netrc',\n",
       " 'compat_opts': set(),\n",
       " 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.17 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'},\n",
       " 'forceprint': {},\n",
       " 'print_to_file': {},\n",
       " 'outtmpl': {'default': '%(title)s [%(id)s].%(ext)s',\n",
       "  'chapter': '%(title)s - %(section_number)03d %(section_title)s [%(id)s].%(ext)s'}}"
      ]
     },
     "execution_count": 26,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "ydl.params"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'format': 'bestaudio/best',\n",
       " 'outtmpl': {'default': 'destinyapp/working_folder/working_audio/raw.%(ext)s',\n",
       "  'chapter': '%(title)s - %(section_number)03d %(section_title)s [%(id)s].%(ext)s'},\n",
       " 'age_limit': 21,\n",
       " 'username': 'oauth2',\n",
       " 'password': '',\n",
       " 'verbose': True,\n",
       " 'compat_opts': set(),\n",
       " 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.17 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'},\n",
       " 'forceprint': {},\n",
       " 'print_to_file': {}}"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "\n",
    "ydl.params"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# command line tests"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "An error occurred: Command '['yt-dlp', '--username', 'oauth2', '--password', '--extract-audio', '-o', 'destinyapp/working_folder/working_audio/raw.%(ext)s', '--age-limit', '21', '--verbose', 'https://www.youtube.com/watch?v=H-XdAZC9U7M']' returned non-zero exit status 1.\n",
      "Error output: [debug] Command-line config: ['--username', 'PRIVATE', '--password', 'PRIVATE', '-o', 'destinyapp/working_folder/working_audio/raw.%(ext)s', '--age-limit', '21', '--verbose', 'https://www.youtube.com/watch?v=H-XdAZC9U7M']\n",
      "[debug] Home config \"yt-dlp.conf\": ['{format:', 'bestaudio/best,', 'outtmpl:', '{default:', 'destinyapp/working_folder/working_audio/raw.%(ext)s,', 'chapter:', '%(title)s - %(section_number)03d %(section_title)s [%(id)s].%(ext)s},', 'age_limit:', '21,', 'username:', 'oauth2,', 'password:', ',', 'compat_opts:', 'set(),', 'http_headers:', '{User-Agent:', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.17 Safari/537.36,', 'Accept:', 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8,', 'Accept-Language:', 'en-us,en;q=0.5,', 'Sec-Fetch-Mode:', 'navigate},', 'forceprint:', '{},', 'print_to_file:', '{}}']\n",
      "[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)\n",
      "[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (pip)\n",
      "[debug] Python 3.11.3 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)\n",
      "[debug] exe versions: ffmpeg N-115469-g4008a80c1b-20240531 (setts), ffprobe N-115469-g4008a80c1b-20240531\n",
      "[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.40.1, urllib3-2.2.1, websockets-12.0\n",
      "[debug] Proxy map: {'backend': 'https://destinyrecaps.com'}\n",
      "[debug] Request Handlers: urllib, requests, websockets\n",
      "[debug] Extractor Plugins: oauth2 (YoutubeBaseInfoExtractor), oauth2 (YoutubeClipIE), oauth2 (YoutubeConsentRedirectIE), oauth2 (YoutubeFavouritesIE), oauth2 (YoutubeIE), oauth2 (YoutubeMusicSearchURLIE), oauth2 (YoutubeNotificationsIE), oauth2 (YoutubeSearchDateIE), oauth2 (YoutubeSearchIE), oauth2 (YoutubeSearchURLIE), oauth2 (YoutubeTabBaseInfoExtractor), oauth2 (YoutubeTabIE)\n",
      "[debug] Plugin directories: ['D:\\\\DestinyFolder\\\\env\\\\Lib\\\\site-packages\\\\yt_dlp_plugins']\n",
      "[debug] Loaded 1820 extractors\n",
      "ERROR: [generic] '{format:' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:{format:\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: [generic] 'bestaudio/best,' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:bestaudio/best,\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: Unable to handle request: Unsupported url scheme: \"outtmpl\" (requests, urllib, websockets)\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 1606, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 1741, in __extract_info\n",
      "    ie_result = ie.extract(url)\n",
      "                ^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2376, in _real_extract\n",
      "    full_response = self._request_webpage(url, video_id, headers=filter_dict({\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 890, in _request_webpage\n",
      "    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 4142, in urlopen\n",
      "    return self._request_director.send(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\networking\\common.py\", line 130, in send\n",
      "    raise NoSupportingHandlers(unsupported_errors, unexpected_errors)\n",
      "yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Unsupported url scheme: \"outtmpl\" (requests, urllib, websockets)\n",
      "\n",
      "ERROR: [generic] '{default:' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:{default:\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: [generic] 'destinyapp/working_folder/working_audio/raw.%(ext)s,' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:destinyapp/working_folder/working_audio/raw.%(ext)s,\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: Unable to handle request: Unsupported url scheme: \"chapter\" (requests, urllib, websockets)\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 1606, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 1741, in __extract_info\n",
      "    ie_result = ie.extract(url)\n",
      "                ^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2376, in _real_extract\n",
      "    full_response = self._request_webpage(url, video_id, headers=filter_dict({\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 890, in _request_webpage\n",
      "    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 4142, in urlopen\n",
      "    return self._request_director.send(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\networking\\common.py\", line 130, in send\n",
      "    raise NoSupportingHandlers(unsupported_errors, unexpected_errors)\n",
      "yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Unsupported url scheme: \"chapter\" (requests, urllib, websockets)\n",
      "\n",
      "ERROR: [generic] '%(title)s - %(section_number)03d %(section_title)s [%(id)s].%(ext)s},' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:%(title)s - %(section_number)03d %(section_title)s [%(id)s].%(ext)s},\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: [generic] 'age_limit:' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:age_limit:\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: [generic] '21,' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:21,\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: Unable to handle request: Unsupported url scheme: \"username\" (requests, urllib, websockets)\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 1606, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 1741, in __extract_info\n",
      "    ie_result = ie.extract(url)\n",
      "                ^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2376, in _real_extract\n",
      "    full_response = self._request_webpage(url, video_id, headers=filter_dict({\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 890, in _request_webpage\n",
      "    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 4142, in urlopen\n",
      "    return self._request_director.send(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\networking\\common.py\", line 130, in send\n",
      "    raise NoSupportingHandlers(unsupported_errors, unexpected_errors)\n",
      "yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Unsupported url scheme: \"username\" (requests, urllib, websockets)\n",
      "\n",
      "ERROR: [generic] 'oauth2,' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:oauth2,\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: Unable to handle request: Unsupported url scheme: \"password\" (requests, urllib, websockets)\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 1606, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 1741, in __extract_info\n",
      "    ie_result = ie.extract(url)\n",
      "                ^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2376, in _real_extract\n",
      "    full_response = self._request_webpage(url, video_id, headers=filter_dict({\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 890, in _request_webpage\n",
      "    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 4142, in urlopen\n",
      "    return self._request_director.send(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\networking\\common.py\", line 130, in send\n",
      "    raise NoSupportingHandlers(unsupported_errors, unexpected_errors)\n",
      "yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Unsupported url scheme: \"password\" (requests, urllib, websockets)\n",
      "\n",
      "ERROR: [generic] ',' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:,\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: [generic] 'compat_opts:' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:compat_opts:\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: [generic] 'set(),' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:set(),\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: [generic] 'http_headers:' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:http_headers:\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: [generic] '{User-Agent:' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:{User-Agent:\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: [generic] 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.17 Safari/537.36,' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.17 Safari/537.36,\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: Unable to handle request: Unsupported url scheme: \"accept\" (requests, urllib, websockets)\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 1606, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 1741, in __extract_info\n",
      "    ie_result = ie.extract(url)\n",
      "                ^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2376, in _real_extract\n",
      "    full_response = self._request_webpage(url, video_id, headers=filter_dict({\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 890, in _request_webpage\n",
      "    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 4142, in urlopen\n",
      "    return self._request_director.send(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\networking\\common.py\", line 130, in send\n",
      "    raise NoSupportingHandlers(unsupported_errors, unexpected_errors)\n",
      "yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Unsupported url scheme: \"accept\" (requests, urllib, websockets)\n",
      "\n",
      "ERROR: [generic] 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8,' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8,\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: Unable to handle request: Unsupported url scheme: \"accept-language\" (requests, urllib, websockets)\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 1606, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 1741, in __extract_info\n",
      "    ie_result = ie.extract(url)\n",
      "                ^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2376, in _real_extract\n",
      "    full_response = self._request_webpage(url, video_id, headers=filter_dict({\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 890, in _request_webpage\n",
      "    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 4142, in urlopen\n",
      "    return self._request_director.send(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\networking\\common.py\", line 130, in send\n",
      "    raise NoSupportingHandlers(unsupported_errors, unexpected_errors)\n",
      "yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Unsupported url scheme: \"accept-language\" (requests, urllib, websockets)\n",
      "\n",
      "ERROR: [generic] 'en-us,en;q=0.5,' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:en-us,en;q=0.5,\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: Unable to handle request: Unsupported url scheme: \"sec-fetch-mode\" (requests, urllib, websockets)\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 1606, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 1741, in __extract_info\n",
      "    ie_result = ie.extract(url)\n",
      "                ^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2376, in _real_extract\n",
      "    full_response = self._request_webpage(url, video_id, headers=filter_dict({\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 890, in _request_webpage\n",
      "    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 4142, in urlopen\n",
      "    return self._request_director.send(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\networking\\common.py\", line 130, in send\n",
      "    raise NoSupportingHandlers(unsupported_errors, unexpected_errors)\n",
      "yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Unsupported url scheme: \"sec-fetch-mode\" (requests, urllib, websockets)\n",
      "\n",
      "ERROR: [generic] 'navigate},' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:navigate},\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: Unable to handle request: Unsupported url scheme: \"forceprint\" (requests, urllib, websockets)\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 1606, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 1741, in __extract_info\n",
      "    ie_result = ie.extract(url)\n",
      "                ^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2376, in _real_extract\n",
      "    full_response = self._request_webpage(url, video_id, headers=filter_dict({\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 890, in _request_webpage\n",
      "    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 4142, in urlopen\n",
      "    return self._request_director.send(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\networking\\common.py\", line 130, in send\n",
      "    raise NoSupportingHandlers(unsupported_errors, unexpected_errors)\n",
      "yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Unsupported url scheme: \"forceprint\" (requests, urllib, websockets)\n",
      "\n",
      "ERROR: [generic] '{},' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:{},\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: [generic] 'print_to_file:' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:print_to_file:\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: [generic] '{}}' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:{}}\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "[debug] Loading youtube-oauth2.token_data from cache\n",
      "WARNING: [youtube+oauth2] H-XdAZC9U7M: nsig extraction failed: You may experience throttling for some formats\n",
      "         n = UomrbLMy1QfW5y- ; player = https://www.youtube.com/s/player/37b24ccb/player_ias.vflset/en_US/base.js\n",
      "[debug] [youtube+oauth2] Unable to extract nsig function code (caused by RegexNotFoundError('Unable to extract Initial JS player n function name; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U\n",
      "WARNING: [youtube+oauth2] H-XdAZC9U7M: nsig extraction failed: You may experience throttling for some formats\n",
      "         n = 3uD3-OvCNRRtMRs ; player = https://www.youtube.com/s/player/37b24ccb/player_ias.vflset/en_US/base.js\n",
      "[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto\n",
      "[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id\n",
      "[debug] Default format spec: bestvideo*+bestaudio/best\n",
      "[debug] File locking is not supported. Proceeding without locking\n",
      "[debug] Invoking hlsnative downloader on \"https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1723510994/ei/cly6ZpfQIZzVzN0PqYjm8Qw/ip/75.49.124.126/id/1fe5dd0190bd53b3/itag/609/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/wft/1/sgovp/clen%3D17538010%3Bdur%3D187.833%3Bgir%3Dyes%3Bitag%3D247%3Blmt%3D1723430283301890/rqh/1/hls_chunk_host/rr4---sn-q4flrnss.googlevideo.com/xpc/EgVo2aDSNQ%3D%3D/mh/xb/mm/31,29/mn/sn-q4flrnss,sn-q4fl6ns6/ms/au,rdu/mv/m/mvi/4/pl/21/initcwndbps/657500/siu/1/vprv/1/playlist_type/DVR/dover/13/txp/530F224/mt/1723489016/fvip/5/short_key/1/keepalive/yes/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,wft,sgovp,rqh,xpc,siu,vprv,playlist_type/sig/AJfQdSswRAIgG40phxDnMg8swT8UGOnfA3x4Sv2U7OqgyTmkXFZf4KQCIA2NFAMcOGe0ruVeTecQHNumOcJhHSaOPF2_WJfH9vwT/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AGtxev0wRAIgY21oYSRW4osxOTMrgV60RFGZY3UphaDbIqpXcOXzHb4CIDk00Lm6KiB_Gi_Bs5vBsOWP61e4DI03SJJV5BwsTkUC/playlist/index.m3u8\"\n",
      "[debug] Invoking http downloader on \"https://rr4---sn-q4flrnss.googlevideo.com/videoplayback?expire=1723510994&ei=cly6ZpfQIZzVzN0PqYjm8Qw&ip=75.49.124.126&id=o-ALjdWRQuENZlHvDI3rRGpPdoZtv6yFVtrsk-GdBDTIDG&itag=140&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=xb&mm=31%2C29&mn=sn-q4flrnss%2Csn-q4fl6ns6&ms=au%2Crdu&mv=m&mvi=4&pl=21&initcwndbps=657500&siu=1&vprv=1&svpuc=1&mime=audio%2Fmp4&rqh=1&gir=yes&clen=3041660&dur=187.895&lmt=1723430289416374&mt=1723489016&fvip=5&keepalive=yes&c=IOS&txp=5318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Csiu%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAIvPoGO2ATYpDWGouw-LU1z3qhgtlDehsxVQXVNYU0mrAiBOIv5hPUjFBeZmYXCXAkvbNKB4bFLIBRlPJtBYcGSL5w%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRQIgPWoMLinO00rnqa6zrqIpUK5-PRs16LeHoqIuLVM5wvYCIQDnPqIKwFQHDvZfZYDISLqqnGoNs0zFDpn0F8Z00VjvuQ%3D%3D\"\n",
      "[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:destinyapp\\working_folder\\working_audio\\raw.f609.mp4 -i file:destinyapp\\working_folder\\working_audio\\raw.f140.m4a -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart file:destinyapp\\working_folder\\working_audio\\raw.temp.mp4\n",
      "\n"
     ]
    }
   ],
   "source": [
    "import subprocess\n",
    "\n",
    "folder_path = \"destinyapp/working_folder/working_audio/\"\n",
    "\n",
    "ydl_opts = {\n",
    "    'format': 'bestaudio/best',\n",
    "    'outtmpl': folder_path + 'raw' + '.%(ext)s',\n",
    "    'age_limit': 21,\n",
    "    'username': 'oauth2',\n",
    "    'password': '',\n",
    "    'verbose': True,\n",
    "}\n",
    "\n",
    "video_id=\"H-XdAZC9U7M\"\n",
    "\n",
    "# Construct the yt-dlp command\n",
    "url = \"https://www.youtube.com/watch?v=\"+video_id  # Replace with your desired URL\n",
    "command = [\n",
    "    \"yt-dlp\",\n",
    "    \"--username\", \"oauth2\",\n",
    "    \"--password\", \"\",\n",
    "    \"--extract-audio\",\n",
    "    \"-o\", ydl_opts['outtmpl'],\n",
    "    \"--age-limit\", str(ydl_opts['age_limit']),\n",
    "    \"--verbose\" if ydl_opts['verbose'] else \"\",\n",
    "    url,\n",
    "]\n",
    "\n",
    "\n",
    "command = [arg for arg in command if arg]\n",
    "\n",
    "# Execute the command\n",
    "try:\n",
    "    result = subprocess.run(command, check=True, capture_output=True, text=True)\n",
    "    print(\"Command output:\", result.stdout)\n",
    "except subprocess.CalledProcessError as e:\n",
    "    print(\"An error occurred:\", e)\n",
    "    print(\"Error output:\", e.stderr)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['yt-dlp', '-f', 'bestaudio/best', '-o', 'destinyapp/working_folder/working_audio/raw.%(ext)s', '--age-limit', '21', '--username', 'oauth2', '--password', '--verbose', '-x', 'https://www.youtube.com/watch?v=H-XdAZC9U7M']\n"
     ]
    }
   ],
   "source": [
    "print(command)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "yt-dlp --extract-audio --verbose --username oauth2 --password '' --URL https://www.youtube.com/watch?v=H-XdAZC9U7M"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "yt-dlp --verbose --username oauth2 --password '' -x https://www.youtube.com/watch?v=H-XdAZC9U7M"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "folder_path = \"destinyapp/working_folder/working_audio/\"\n",
    "'outtmpl': folder_path + 'raw' + '.%(ext)s',"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "import subprocess\n",
    "\n",
    "folder_path = \"destinyapp/working_folder/working_audio/\"\n",
    "# output_path=\"\\\"\"+folder_path + 'raw' + '.%(ext)s'+\"\\\"\"\n",
    "output_path=folder_path + 'raw.%(ext)s'\n",
    "command=['yt-dlp', '--format', 'bestaudio/best', '-o', output_path, '--verbose', '--username', 'oauth2', '--password', '\"\"', '-x', '--', 'https://www.youtube.com/watch?v=H-XdAZC9U7M']\n",
    "try: \n",
    "    result = subprocess.run(command, check=True, capture_output=True, text=True)\n",
    "except Exception as e:\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "yt-dlp --format bestaudio/best -o destinyapp/working_folder/working_audio/raw.%(ext)s --verbose --username oauth2 --password \"\" -x -- https://www.youtube.com/watch?v=H-XdAZC9U7M\n"
     ]
    }
   ],
   "source": [
    "print(\" \".join(command))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 45,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Ethan ErrorAn error occurred: Command '['yt-dlp', '--format', 'bestaudio/best', '-o', 'destinyapp/working_folder/working_audio/raw.%(ext)s', '--verbose', '--username', 'oauth2', '--password', '\"\"', '-x', '--', 'https://www.youtube.com/watch?v=H-XdAZC9U7M']' returned non-zero exit status 1.\n",
      "Ethan ErrorError output: [debug] Command-line config: ['--format', 'bestaudio/best', '-o', 'destinyapp/working_folder/working_audio/raw.%(ext)s', '--verbose', '--username', 'PRIVATE', '--password', 'PRIVATE', '-x', '--', 'https://www.youtube.com/watch?v=H-XdAZC9U7M']\n",
      "[debug] Home config \"yt-dlp.conf\": ['{format:', 'bestaudio/best,', 'outtmpl:', '{default:', 'destinyapp/working_folder/working_audio/raw.%(ext)s,', 'chapter:', '%(title)s - %(section_number)03d %(section_title)s [%(id)s].%(ext)s},', 'age_limit:', '21,', 'username:', 'oauth2,', 'password:', ',', 'compat_opts:', 'set(),', 'http_headers:', '{User-Agent:', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.17 Safari/537.36,', 'Accept:', 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8,', 'Accept-Language:', 'en-us,en;q=0.5,', 'Sec-Fetch-Mode:', 'navigate},', 'forceprint:', '{},', 'print_to_file:', '{}}']\n",
      "[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)\n",
      "[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (pip)\n",
      "[debug] Python 3.11.3 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)\n",
      "[debug] exe versions: ffmpeg N-115469-g4008a80c1b-20240531 (setts), ffprobe N-115469-g4008a80c1b-20240531\n",
      "[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.40.1, urllib3-2.2.1, websockets-12.0\n",
      "[debug] Proxy map: {'backend': 'https://destinyrecaps.com'}\n",
      "[debug] Request Handlers: urllib, requests, websockets\n",
      "[debug] Extractor Plugins: oauth2 (YoutubeBaseInfoExtractor), oauth2 (YoutubeClipIE), oauth2 (YoutubeConsentRedirectIE), oauth2 (YoutubeFavouritesIE), oauth2 (YoutubeIE), oauth2 (YoutubeMusicSearchURLIE), oauth2 (YoutubeNotificationsIE), oauth2 (YoutubeSearchDateIE), oauth2 (YoutubeSearchIE), oauth2 (YoutubeSearchURLIE), oauth2 (YoutubeTabBaseInfoExtractor), oauth2 (YoutubeTabIE)\n",
      "[debug] Plugin directories: ['D:\\\\DestinyFolder\\\\env\\\\Lib\\\\site-packages\\\\yt_dlp_plugins']\n",
      "[debug] Loaded 1820 extractors\n",
      "ERROR: [generic] '{format:' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:{format:\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: [generic] 'bestaudio/best,' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:bestaudio/best,\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: Unable to handle request: Unsupported url scheme: \"outtmpl\" (requests, urllib, websockets)\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 1606, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 1741, in __extract_info\n",
      "    ie_result = ie.extract(url)\n",
      "                ^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2376, in _real_extract\n",
      "    full_response = self._request_webpage(url, video_id, headers=filter_dict({\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 890, in _request_webpage\n",
      "    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 4142, in urlopen\n",
      "    return self._request_director.send(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\networking\\common.py\", line 130, in send\n",
      "    raise NoSupportingHandlers(unsupported_errors, unexpected_errors)\n",
      "yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Unsupported url scheme: \"outtmpl\" (requests, urllib, websockets)\n",
      "\n",
      "ERROR: [generic] '{default:' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:{default:\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: [generic] 'destinyapp/working_folder/working_audio/raw.%(ext)s,' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:destinyapp/working_folder/working_audio/raw.%(ext)s,\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: Unable to handle request: Unsupported url scheme: \"chapter\" (requests, urllib, websockets)\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 1606, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 1741, in __extract_info\n",
      "    ie_result = ie.extract(url)\n",
      "                ^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2376, in _real_extract\n",
      "    full_response = self._request_webpage(url, video_id, headers=filter_dict({\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 890, in _request_webpage\n",
      "    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 4142, in urlopen\n",
      "    return self._request_director.send(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\networking\\common.py\", line 130, in send\n",
      "    raise NoSupportingHandlers(unsupported_errors, unexpected_errors)\n",
      "yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Unsupported url scheme: \"chapter\" (requests, urllib, websockets)\n",
      "\n",
      "ERROR: [generic] '%(title)s - %(section_number)03d %(section_title)s [%(id)s].%(ext)s},' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:%(title)s - %(section_number)03d %(section_title)s [%(id)s].%(ext)s},\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: [generic] 'age_limit:' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:age_limit:\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: [generic] '21,' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:21,\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: Unable to handle request: Unsupported url scheme: \"username\" (requests, urllib, websockets)\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 1606, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 1741, in __extract_info\n",
      "    ie_result = ie.extract(url)\n",
      "                ^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2376, in _real_extract\n",
      "    full_response = self._request_webpage(url, video_id, headers=filter_dict({\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 890, in _request_webpage\n",
      "    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 4142, in urlopen\n",
      "    return self._request_director.send(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\networking\\common.py\", line 130, in send\n",
      "    raise NoSupportingHandlers(unsupported_errors, unexpected_errors)\n",
      "yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Unsupported url scheme: \"username\" (requests, urllib, websockets)\n",
      "\n",
      "ERROR: [generic] 'oauth2,' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:oauth2,\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: Unable to handle request: Unsupported url scheme: \"password\" (requests, urllib, websockets)\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 1606, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 1741, in __extract_info\n",
      "    ie_result = ie.extract(url)\n",
      "                ^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2376, in _real_extract\n",
      "    full_response = self._request_webpage(url, video_id, headers=filter_dict({\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 890, in _request_webpage\n",
      "    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 4142, in urlopen\n",
      "    return self._request_director.send(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\networking\\common.py\", line 130, in send\n",
      "    raise NoSupportingHandlers(unsupported_errors, unexpected_errors)\n",
      "yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Unsupported url scheme: \"password\" (requests, urllib, websockets)\n",
      "\n",
      "ERROR: [generic] ',' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:,\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: [generic] 'compat_opts:' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:compat_opts:\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: [generic] 'set(),' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:set(),\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: [generic] 'http_headers:' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:http_headers:\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: [generic] '{User-Agent:' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:{User-Agent:\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: [generic] 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.17 Safari/537.36,' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.17 Safari/537.36,\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: Unable to handle request: Unsupported url scheme: \"accept\" (requests, urllib, websockets)\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 1606, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 1741, in __extract_info\n",
      "    ie_result = ie.extract(url)\n",
      "                ^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2376, in _real_extract\n",
      "    full_response = self._request_webpage(url, video_id, headers=filter_dict({\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 890, in _request_webpage\n",
      "    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 4142, in urlopen\n",
      "    return self._request_director.send(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\networking\\common.py\", line 130, in send\n",
      "    raise NoSupportingHandlers(unsupported_errors, unexpected_errors)\n",
      "yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Unsupported url scheme: \"accept\" (requests, urllib, websockets)\n",
      "\n",
      "ERROR: [generic] 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8,' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8,\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: Unable to handle request: Unsupported url scheme: \"accept-language\" (requests, urllib, websockets)\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 1606, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 1741, in __extract_info\n",
      "    ie_result = ie.extract(url)\n",
      "                ^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2376, in _real_extract\n",
      "    full_response = self._request_webpage(url, video_id, headers=filter_dict({\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 890, in _request_webpage\n",
      "    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 4142, in urlopen\n",
      "    return self._request_director.send(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\networking\\common.py\", line 130, in send\n",
      "    raise NoSupportingHandlers(unsupported_errors, unexpected_errors)\n",
      "yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Unsupported url scheme: \"accept-language\" (requests, urllib, websockets)\n",
      "\n",
      "ERROR: [generic] 'en-us,en;q=0.5,' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:en-us,en;q=0.5,\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: Unable to handle request: Unsupported url scheme: \"sec-fetch-mode\" (requests, urllib, websockets)\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 1606, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 1741, in __extract_info\n",
      "    ie_result = ie.extract(url)\n",
      "                ^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2376, in _real_extract\n",
      "    full_response = self._request_webpage(url, video_id, headers=filter_dict({\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 890, in _request_webpage\n",
      "    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 4142, in urlopen\n",
      "    return self._request_director.send(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\networking\\common.py\", line 130, in send\n",
      "    raise NoSupportingHandlers(unsupported_errors, unexpected_errors)\n",
      "yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Unsupported url scheme: \"sec-fetch-mode\" (requests, urllib, websockets)\n",
      "\n",
      "ERROR: [generic] 'navigate},' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:navigate},\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: Unable to handle request: Unsupported url scheme: \"forceprint\" (requests, urllib, websockets)\n",
      "Traceback (most recent call last):\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 1606, in wrapper\n",
      "    return func(self, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 1741, in __extract_info\n",
      "    ie_result = ie.extract(url)\n",
      "                ^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2376, in _real_extract\n",
      "    full_response = self._request_webpage(url, video_id, headers=filter_dict({\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 890, in _request_webpage\n",
      "    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\YoutubeDL.py\", line 4142, in urlopen\n",
      "    return self._request_director.send(req)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\networking\\common.py\", line 130, in send\n",
      "    raise NoSupportingHandlers(unsupported_errors, unexpected_errors)\n",
      "yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Unsupported url scheme: \"forceprint\" (requests, urllib, websockets)\n",
      "\n",
      "ERROR: [generic] '{},' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:{},\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: [generic] 'print_to_file:' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:print_to_file:\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "ERROR: [generic] '{}}' is not a valid URL. Set --default-search \"ytsearch\" (or run  yt-dlp \"ytsearch:{}}\" ) to search YouTube\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\common.py\", line 734, in extract\n",
      "    ie_result = self._real_extract(url)\n",
      "                ^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"D:\\DestinyFolder\\env\\Lib\\site-packages\\yt_dlp\\extractor\\generic.py\", line 2349, in _real_extract\n",
      "    raise ExtractorError(\n",
      "\n",
      "[debug] Loading youtube-oauth2.token_data from cache\n",
      "WARNING: [youtube+oauth2] H-XdAZC9U7M: nsig extraction failed: You may experience throttling for some formats\n",
      "         n = Vju0pl_ZmDaVzx7 ; player = https://www.youtube.com/s/player/37b24ccb/player_ias.vflset/en_US/base.js\n",
      "[debug] [youtube+oauth2] Unable to extract nsig function code (caused by RegexNotFoundError('Unable to extract Initial JS player n function name; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U\n",
      "WARNING: [youtube+oauth2] H-XdAZC9U7M: nsig extraction failed: You may experience throttling for some formats\n",
      "         n = nIQYozinrD7CB9e ; player = https://www.youtube.com/s/player/37b24ccb/player_ias.vflset/en_US/base.js\n",
      "[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto\n",
      "[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id\n",
      "[debug] Invoking http downloader on \"https://rr4---sn-q4flrnss.googlevideo.com/videoplayback?expire=1723512285&ei=fWG6Zr6aDeXVir4Pv97ZuQY&ip=75.49.124.126&id=o-AHnuS0MQFq_oZIzkIB0xq4ylyhi_3RUqphg_593T-0Ac&itag=140&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=xb&mm=31%2C29&mn=sn-q4flrnss%2Csn-q4fl6ns6&ms=au%2Crdu&mv=m&mvi=4&pl=21&initcwndbps=653750&siu=1&vprv=1&svpuc=1&mime=audio%2Fmp4&rqh=1&gir=yes&clen=3041660&dur=187.895&lmt=1723430289416374&mt=1723490220&fvip=5&keepalive=yes&c=IOS&txp=5318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Csiu%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhALix-lCQy2Usc2Bhvm48gdIMWxufkJQg__nLxOCrwa7tAiEAvsOAhq4UN7tafOkXMQJUy-EVpssyEs_w1KlO6m__4tk%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRQIge-a2aapQyPgK1K9r47U4A5vC6KNEnYwQGZfgsp8QZc8CIQD2tJkmo7klrDT-dbdBBNo3LWta4VUWn8z5KFcyxL69VA%3D%3D\"\n",
      "[debug] File locking is not supported. Proceeding without locking\n",
      "[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:destinyapp\\working_folder\\working_audio\\raw.m4a -map 0 -dn -ignore_unknown -c copy -f mp4 -movflags +faststart file:destinyapp\\working_folder\\working_audio\\raw.temp.m4a\n",
      "\n"
     ]
    }
   ],
   "source": [
    "try: \n",
    "    result = subprocess.run(command, check=True, capture_output=True, text=True)\n",
    "    print(\"Command output:\", result.stdout)\n",
    "except subprocess.CalledProcessError as e:\n",
    "    print(\"Ethan ErrorAn error occurred:\", e)\n",
    "    # print(\"Ethan ErrorError output:\", e.stderr)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "env",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
